services:
  pg:
    image: postgres:16
    env_file: .env
    environment:
      POSTGRES_USER: $VITE_DATABASE_SUB_USER
      POSTGRES_PASSWORD: $VITE_DATABASE_SUB_PASSWORD
      POSTGRES_DB: $VITE_DATABASE_SUB_NAME
    ports:
      - "${VITE_DATABASE_SUB_PORT}:5432"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
